// Code generated by protoc-gen-go.
// source: spec.proto
// DO NOT EDIT!

/*
Package example is a generated protocol buffer package.

It is generated from these files:
	spec.proto

It has these top-level messages:
	Company
	Employee
*/
package example

import proto "github.com/gogo/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type CompanyType int32

const (
	CompanyType_Private   CompanyType = 17
	CompanyType_Public    CompanyType = 18
	CompanyType_NonProfit CompanyType = 19
)

var CompanyType_name = map[int32]string{
	17: "Private",
	18: "Public",
	19: "NonProfit",
}
var CompanyType_value = map[string]int32{
	"Private":   17,
	"Public":    18,
	"NonProfit": 19,
}

func (x CompanyType) Enum() *CompanyType {
	p := new(CompanyType)
	*p = x
	return p
}
func (x CompanyType) String() string {
	return proto.EnumName(CompanyType_name, int32(x))
}
func (x *CompanyType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CompanyType_value, data, "CompanyType")
	if err != nil {
		return err
	}
	*x = CompanyType(value)
	return nil
}

type Company struct {
	Name             *string          `protobuf:"bytes,1,req" json:"Name,omitempty"`
	Employees        []*Employee      `protobuf:"bytes,2,rep" json:"Employees,omitempty"`
	Type             *CompanyType     `protobuf:"varint,3,req,enum=example.CompanyType" json:"Type,omitempty"`
	Address          *Company_Address `protobuf:"group,4,opt" json:"address,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Company) Reset()         { *m = Company{} }
func (m *Company) String() string { return proto.CompactTextString(m) }
func (*Company) ProtoMessage()    {}

func (m *Company) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Company) GetEmployees() []*Employee {
	if m != nil {
		return m.Employees
	}
	return nil
}

func (m *Company) GetType() CompanyType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return CompanyType_Private
}

func (m *Company) GetAddress() *Company_Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type Company_Address struct {
	Country          *string `protobuf:"bytes,5,req" json:"Country,omitempty"`
	City             *string `protobuf:"bytes,6,req" json:"City,omitempty"`
	Street           *string `protobuf:"bytes,7,opt" json:"Street,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Company_Address) Reset()         { *m = Company_Address{} }
func (m *Company_Address) String() string { return proto.CompactTextString(m) }
func (*Company_Address) ProtoMessage()    {}

func (m *Company_Address) GetCountry() string {
	if m != nil && m.Country != nil {
		return *m.Country
	}
	return ""
}

func (m *Company_Address) GetCity() string {
	if m != nil && m.City != nil {
		return *m.City
	}
	return ""
}

func (m *Company_Address) GetStreet() string {
	if m != nil && m.Street != nil {
		return *m.Street
	}
	return ""
}

type Employee struct {
	Name             *string `protobuf:"bytes,1,req" json:"Name,omitempty"`
	SSN              *string `protobuf:"bytes,2,opt" json:"SSN,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Employee) Reset()         { *m = Employee{} }
func (m *Employee) String() string { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()    {}

func (m *Employee) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Employee) GetSSN() string {
	if m != nil && m.SSN != nil {
		return *m.SSN
	}
	return ""
}

func init() {
	proto.RegisterEnum("example.CompanyType", CompanyType_name, CompanyType_value)
}
